#+TITLE:     Virtual Satellite Image Processing and Analysis Laboratory
#+AUTHOR:    A.V.Ravi kiran
#+AUTHOR:    Siddhartha Chaki
#+EMAIL:     me15btech11039@iith.ac.in
#+EMAIL:     siddharthachaki02@gmail.com

#+DESCRIPTION: This document expalins how Virtual Satellite Image Processing and Analysis Laboratory is developed.

** About
This is an offline application,user has to download the lab,install all the required softwares and then then run the lab.\\
This lab is about image processing in which user inputs a image,selects required controls,clicks on submit and then image is processed and
displayed to user.

** Aproach
This lab uses Scialb for processing the images and python is used to call scilab and to build user interface.

** Technologies Used:

- *Scilab*
 + SIVP Toolbox

- *Python2*
 + pip
 + Kivy
 + Scilab2py
 + scipy
 + numpy
 + pygame

- *OpenCV*

Note: 1.This lab works only with python2 but not python3.
      2.Installation procedure is given in user manual.

** Development Envinorment:
 - OS: Ubuntu 14.04, 64 bit
 - Text Editor: Atom
 - Python 2.7.6
 - Scilab 5.5.0
 - kivy 1.9.2

** Understnding Files

 - This lab contains six experiments
  + is in exp1 folder
  + is in exp2 folder
  + is in exp3 folder
  + is in exp4 folder
  + is in exp5 folder
  + is in exp6 folder

 - In each folder there are two files named experiment(number).py and experiment(number).kv
  * experiment(number).kv is a kivy file which contains the layout of the experiment GUI.kivy is used to build GUI.
  * experiment(number).py which is a python file contains all the functionality of recieving inputs,validating inputs,calling scilab,creating\\
    folders and displaying output images.

 - In each folder there are few files with extension of .sci,these are scilab files.These files are used to process images and produce output images.
 - Here's the list of scilab files which are called from python.
  * Exp1 -
  * Exp2 -
  * Exp3 -
  * Exp4 -
  * Exp5 -
  * Exp6 -

** How it works?

 - When button with Experiment name is clicked in main menu,the python file experiment(number).py present in exp(number) directory is called.This
 file has a class named 'Experiment(number)App'.This class contains all the functions to handle inputs,call scilab and display output images.
 - Here are some of the common functions present in all experiments

 - show_filechooser(arguments):
  * This function is called when 'Input Image' button is clicked.
  * This function makek the main image transparent (changes main image source to 'no.gif') and displays file selector.(by deafult the height of
    filechooser is set to 0,this function changes height to non-zero value, hence displaying the filechooser)

 - show_selected_img(arguments):
  * This function is called when image file is selected in file chooser.
  * Closes the file chooser (.i.e changes the height to 0)
  * This function changes the source of main image to selected image,hence selected image is displayed.
  * Displays image name below the image.
  * Note: For Exp1 : Finds the height and width of selected image and adjusts the ranges of rowstart,rowend.columnstart and columnend.

 - enable_band(arguments):
  * This function is called when image is selected.
  * This function checks whether input file has any extension (.jpg,.gif),if not it is assumed to be raw HDR image and band value text field is enabled.
  * Band value is disabled by default because it's value is 3 for all image formats expect HDR,if image is HDR user should input no of bands.

 - set_max_rgb(arguments):
  * This function is called when user inputs band value.
  * This function changes the max of R,G,B values to input band value.
  * Also updates the hint text to updated range.

 - change_slider(arguments):
  * This function is called when user inputs value in text field which are present side by sliders.
  * Changes the value of slider to input value in text field.
  * Sets the value of slider to max when users inputs value greater than range(and also for minimum)

 - main_menu(arguments):
  * This function is called when 'Main Menu' button is clicked.
