#+TITLE:     Virtual Satellite Image Processing and Analysis Laboratory
#+AUTHOR:    A.V.Ravi kiran
#+AUTHOR:    Siddhartha Chaki
#+EMAIL:     me15btech11039@iith.ac.in
#+EMAIL:     siddharthachaki02@gmail.com

#+DESCRIPTION: This document contains all the information of Virtual Satellite Image Processing and Analysis Laboratory.

** About
This is an offline application,user has to download the lab,install all the required softwares and then then run the lab.\\
This lab is about image processing in which user inputs a image,selects required controls,clicks on submit and then image is processed and displayed to user.

** Aproach
This lab uses Scialb for processing the images and python is used to call scilab and to build user interface.

** Technologies Used:

- *Scilab*
 + SIVP Toolbox 
 
- *Python2*
 + pip
 + Kivy
 + Scilab2py
 + scipy
 + numpy
 + pygame

- *OpenCV*

Note: This lab works only with python2 but not python3.

** Installation Guide

*** For Ubuntu:

**** For automatic installation

- Download the folder and click on install icon.
- Password is required for installation.
- Approximatey 300MB of data is downloaded and all required softwares are autoamatically installed.

Note: If any problem arises in automatic installtion,then go for manual installation.

**** Manual Installation

 - Open terminal (Press ctrl + alt +T)
 
 - Update your system
 
#+begin_src org
sudo apt-get update
#+end_src

 - Install Python
 
#+begin_src org
sudo apt-get install python
#+end_src

Note: use python2 only.

 - Install Scilab
 
#+begin_src org
sudo apt-get install scilab -y
#+end_src
 
 - Install openCV
 
 #+begin_src org
sudo apt-get install build-essential
#+end_src

#+begin_src org
sudo apt-get install cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev
#+end_src

- Install SIVP toolbox 

#+begin_src org
scilab-cli  -e "atomsInstall('SIVP'); exit;" -nb
#+end_src

 - Install pip
 
#+begin_src org
sudo apt-get install python-pip
#+end_src

 - Install numpy

#+begin_src org
pip install --user numpy
#+end_src

 or

#+begin_src org
sudo apt-get install python-numpy
#+end_src

 - Install scipy
 
#+begin_src org
pip install --user scipy
#+end_src

or

#+begin_src org
sudo apt-get install python-scipy
#+end_src

 - Install scilab2py
 
#+begin_src org
pip install --user scilab2py
#+end_src

 - Install kivy

#+begin_src org
sudo add-apt-repository ppa:kivy-team/kivy
#+end_src

#+begin_src org
sudo apt-get install python-kivy
#+end_src

For Windows<br/>
scilab
SIVP Toolbox
Python 2.7.any
if python 3.any installed in system then make sure in cmd when you type python it should open python 2.7 not python 3.* 
to change you can change enviorment path
kivy
if you get any depnedency error like widow thing then run this command 
python -m pip install docutils pygments pypiwin32 kivy.deps.sdl2 kivy.deps.glew

You can install scipy and numpy using their wheels.

First install wheel package if it's already not there...

pip install wheel
Just select the package you want from http://www.lfd.uci.edu/~gohlke/pythonlibs/#scipy

Then go to the command line and change the directory to the downloads folder and install the above wheel using pip.

Example:
cd C:\Users\[user]\Downloads
pip install numpy-1.11.3+mkl-cp27-cp27m-win_amd64.whl
pip install scipy-0.18.1-cp35-cp35m-win_amd64.whl

if you get any error like NUMPY_MKL
then uninstall numpy which installed using normal 'pip install numpy'
Becasue scipy whl package need numpy whl package not normal numpy package.


scilab2py
pip install scilab2py
 if you geting any error like
 Scilab not found.  Please see documentation at:
http://blink1073.github.io/scilab2py/source/installation.html
then uninstall wheel using pip uninstall wheel
then install scilab2py using pip install scilab2py


Now we are ready to go




Links:
http://www.lfd.uci.edu/~gohlke/pythonlibs/#scipy
https://stackoverflow.com/questions/26657334/installing-numpy-and-scipy-on-64-bit-windows-with-pip

